---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

This repo contains the material for the pre-conference workshop for Biometrics by the Botanic Gardens (IBS-AR 2019) for Tidyverse and R Markdown.

* **When**: Sunday 1st December 2019 9am-5pm
* **Where**: University of Adelaide North Tce Campus, Hughes 322 Teaching Room
* **Who**: Participants are expected to have basic knowledge of R. To get the most of the workshop, is is desirable that you know LaTeX or HTML/CSS although not necessary.

Register [here](https://ausbiometric2019.org/registration/) for the workshop.

Current tentative schedule is:

Time | Activity 
:----|:---
8.30-8.50 | Registration
8.50-9.00 | Welcome 
9.00-10.30 | **Lesson 1**<Br> Introduction +<br>Data visualisation with `ggplot2` +<br>Interactive graphs with `plotly`
10.30 - 11.00 | **Lesson 2**<br>Data wrangling with dplyr & tidyr Part I
11.00 - 11.30 | *Coffee Break*
11.30 - 12.00 | Data wrangling with dplyr & tidyr Part II
12.00 - 12.30 | **Lesson 3**<br> Functional programming with `purrr` & `furrr`
12.30 - 13.00 | **Lesson 4**<br>R Markdown Basics with `rmarkdown` & `knitr`
13.00 - 13.45 | *Lunch*
13.45 - 15.00 | **Lesson 5** <br> Reproducible Reports with R Markdown 
15.00 - 15.30 | *Tea Break*
15.30 - 16.20 | **Lesson 6**<br> Dynamic Documents with `bookdown`
16.20 - 15.00 | **Lesson 7**<br>Pretty Presentations with `xaringan`

