```{r setup, include = FALSE}
library(tidyverse)
library(agridat)
library(scales)
knitr::opts_chunk$set(
  fig.path = "challenge03/"
)
```

```{r exercise-01}
ggplot(hazell.vegetables, aes(year, celery, fill = celery > 0)) + 
  geom_col(show.legend = FALSE) + 
  geom_hline(yintercept = 0) + 
  scale_y_continuous(labels = dollar) + 
  labs(y = "Gross profit", x = "Year",
       title = "Celery", fill = "Profit") +
  scale_fill_manual(values = c("#ff1a1a", "#008000")) +
  scale_x_discrete(labels = 1:6) + 
  theme(axis.text = element_text(size = 18),
        axis.text.y = element_text(face = "italic"),
        axis.title = element_text(size = 22),
        plot.title = element_text(size = 30, face = "bold",
                                  margin = margin(b = 40),
                                  hjust = -0.8),
        panel.background = element_rect(fill = "transparent"),
        axis.line = element_line(color = "black",
                                 size = 1.3))
```

```{r exercise-02}
ggplot(baker.barley.uniformity, aes(year, yield, group = interaction(row, col))) + 
  geom_point() + 
  geom_line() + 
  labs(y = "Yield", x = "Year", title = "Barley Uniformity Trial") + 
  theme(panel.grid.major = element_line(color = "gray"),
        panel.grid.minor = element_line(color = "gray", linetype = "dashed"),
        panel.background = element_rect(fill = "white"),
        axis.title.y = element_text(margin = margin(r = 10)),
        axis.title.x = element_text(margin = margin(t = 10)))
```

```{r exercise-03}
ggplot(heady.fertilizer, aes(P, yield)) +
geom_point() + facet_wrap(~crop, scale = "free_y") + 
  geom_smooth() + 
  labs(x = "Phosphorous (pounds/acre)",
       y = "Yield"
       ) + 
  theme(plot.background = element_rect(fill = "#CCDFDD", color = "black"),
        strip.background = element_rect(fill = "transparent"),
        panel.background = element_rect(fill = "transparent"))
```

```{r exercise-04}
ggplot(mcleod.barley, aes(year, weight, color = site, size = yield)) + 
  geom_point(alpha = 1/2) + 
  theme_bw(base_size = 18)
```

```{r exercise-05}
ggplot(wallace.iowaland, aes(long, lat, color = yield)) + geom_point(size = 6) +
  scale_color_distiller(palette = "RdYlGn", direction = 1) + 
  labs(y = "Latitude", x = "Longitude") +
  theme(rect = element_rect(fill = "black"),
        text = element_text(color = "white"),
        panel.background = element_rect(fill = "transparent"),
        panel.grid.minor = element_line(linetype = "dashed"),
        axis.text = element_text(color = "gray"))
```


