---
title: "R Markdown Workshop"
subtitle: "Challenge: Tables"
author: "Your Name"
date: "19th November 2019"
output: 
 pdf_document : default
---

## Tables

### LaTeX

* A `pdf` document uses [LaTeX](https://www.latex-project.org/) under the hood to compile a `.tex` file to `pdf`.

* In latex a table is written as (see source Rmd file)


\begin{center}
\begin{tabular}{rr}
\hline
Var1 & Var2 \\
\hline
1 & 2 \\
3 & 4\\
\hline
\end{tabular}
\end{center}

### Markdown 

* A markdown table is written as (see source Rmd file)

| Var1| Var2|
|----:|----:|
|    1|    2|
|    3|    4|


* A table can be created by using `knitr`'s `kable` function as below:


### Using `kable` function 

We'll learn more about code chunks next.

```{r challenge-01}
df <- data.frame(Var1 = c(1, 3),
                 Var2 = c(2, 4))
knitr::kable(df)
```

### HTML 

This is a html table:

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> Var1 </th>
   <th style="text-align:right;"> Var2 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 4 </td>
  </tr>
</tbody>
</table>


## Challenges

1. `knit` this document to get a pdf output and inspect the output. **How did the each of the tables turn out?**
1. Change this document output format to `html` and knit. **What happened to the table written in LaTeX?**


## Advanced challenge

Can you `knit` this document to both `html` and `pdf` simultaneously?

(We'll learn this later.)

